// export const tweetsData = [
//     { tweet: `Crypto is not just about money, it’s about financial freedom and the digital future. #1 🚀\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Every step in the crypto world is a step toward a decentralized future. #2 🌍\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Success in crypto comes to those who dare to innovate and think outside the box. #3 💡\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Don’t just follow the trend, be part of the blockchain technology revolution. #4 🎮\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Crypto teaches us not to fear change, but to embrace it. #5 🎨\n\nAutomate by: @cotabimcotab` },
//     { tweet: `In the world of crypto, patience is key—don’t rush, the journey is long. #6 📱\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Crypto is an investment in future technology, not just an asset. #7 🌟\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Those who lead in crypto are the ones who think differently, not those who follow the crowd. #8 ✨\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Don’t fear volatility, because the biggest opportunities often come from uncertainty. #9 🕹️\n\nAutomate by: @cotabimcotab` },
//     { tweet: `Crypto opens the door to global financial freedom, if we’re brave enough to step through. #10 🏆\n\nAutomate by: @cotabimcotab` },
// ];

export const tweetsData = [
    { tweet: `Donald Trump speaks out against rising crime rates and pledges to strengthen law enforcement. #11 🚔\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump's legal battles intensify as new lawsuits are filed in multiple states. #12 🏛️\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump’s social media platform, Truth Social, sees rapid growth in users. #13 📱\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump makes a surprise appearance at a major rally, energizing his supporters. #14 ⚡\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump expresses frustration with mainstream media coverage and calls for reform. #15 📰\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump's team unveils a new policy proposal aimed at reducing government regulations. #16 📑\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump criticizes President Biden’s foreign policies and promises a stronger U.S. presence globally. #17 🌍\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump’s 2024 campaign kicks off with a strong message on securing the U.S. border. #18 🛑\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump calls for a focus on American energy independence to reduce costs for consumers. #19 ⚡\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump's influence continues to dominate Republican primaries as contenders struggle to gain ground. #20 🔥\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump advocates for lower taxes to stimulate economic growth and job creation. #21 💼\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump releases a new ad campaign focusing on restoring America’s manufacturing base. #22 🏭\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump reaffirms his stance on tough immigration policies as the 2024 election draws near. #23 🚨\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump’s legal team fights back against charges, claiming political bias in ongoing investigations. #24 ⚖️\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump pushes for stronger U.S. military presence in key global hotspots. #25 🦅\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump announces new initiatives aimed at cutting prescription drug prices for Americans. #26 💊\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump vows to tackle China’s trade practices if elected in 2024. #27 🌐\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump ramps up efforts to campaign in key swing states for the 2024 election. #28 🗳️\n\nAutomate by: @cotabimcotab` },
    { tweet: `Donald Trump reiterates his commitment to rebuilding the American economy post-pandemic. #29 💪\n\nAutomate by: @cotabimcotab` },
    { tweet: `Trump makes bold claims about fixing the healthcare system and reducing costs for families. #30 🏥\n\nAutomate by: @cotabimcotab` }
];
